name: Build

on:

  push:
    branches: [ main ]
    paths-ignore:
    - 'doc/**'
    - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Generate test cases
      working-directory: ./Jint.Tests.Test262
      run: dotnet tool restore && dotnet test262 generate

    - name: Test
      run: dotnet test --configuration Release

    - name: Pack with dotnet
      run: dotnet pack --output artifacts --configuration Release -p:PackageVersion=$GITHUB_RUN_ID

    - name: Push with dotnet
      run: dotnet nuget push artifacts/*.nupkg --api-key ${{ secrets.MYGET_API_KEY }} --skip-duplicate --source https://www.myget.org/F/jint/api/v2/package
